-- SQLite Script

PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS Divisions;

CREATE TABLE IF NOT EXISTS Divisions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

DROP TABLE IF EXISTS Posts;

CREATE TABLE IF NOT EXISTS Posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

DROP TABLE IF EXISTS Employees;

CREATE TABLE IF NOT EXISTS Employees (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fio TEXT NOT NULL,
  Divisions_id INTEGER NOT NULL,
  Posts_id INTEGER NOT NULL,
  dateHire DATE NOT NULL,
  dateDismissal DATE,
  FOREIGN KEY (Divisions_id) REFERENCES Divisions (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (Posts_id) REFERENCES Posts (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS Units;

CREATE TABLE IF NOT EXISTS Units (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

DROP TABLE IF EXISTS Locations;

CREATE TABLE IF NOT EXISTS Locations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  Employees_id INTEGER NOT NULL,
  FOREIGN KEY (Employees_id) REFERENCES Employees (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS Products;

CREATE TABLE IF NOT EXISTS Products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  serialNo TEXT NOT NULL,
  Units_id INTEGER NOT NULL,
  Locations_id INTEGER NOT NULL,
  FOREIGN KEY (Units_id) REFERENCES Units (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (Locations_id) REFERENCES Locations (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS Materials;

CREATE TABLE IF NOT EXISTS Materials (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  Units_id INTEGER NOT NULL,
  Locations_id INTEGER NOT NULL,
  count INTEGER NOT NULL,
  price REAL NOT NULL,
  FOREIGN KEY (Units_id) REFERENCES Units (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (Locations_id) REFERENCES Locations (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS Product_Materials;

CREATE TABLE IF NOT EXISTS Product_Materials (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Products_id INTEGER NOT NULL,
  Materials_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  FOREIGN KEY (Products_id) REFERENCES Products (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (Materials_id) REFERENCES Materials (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS Counterparties;

CREATE TABLE IF NOT EXISTS Counterparties (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  legalAddress TEXT NOT NULL,
  phoneNomber TEXT NOT NULL,
  postalAddress TEXT NOT NULL,
  ynp TEXT NOT NULL,
  type TEXT CHECK(type IN ('fiz', 'ur')) NOT NULL DEFAULT 'fiz',
  okulp TEXT,
  okpo TEXT,
  oked TEXT
);

DROP TABLE IF EXISTS Contracts;

CREATE TABLE IF NOT EXISTS Contracts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Counterparties_id INTEGER NOT NULL,
  date DATE NOT NULL,
  summ REAL NOT NULL,
  Products_id INTEGER NOT NULL,
  count INTEGER NOT NULL,
  FOREIGN KEY (Counterparties_id) REFERENCES Counterparties (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (Products_id) REFERENCES Products (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS Receipts;

CREATE TABLE IF NOT EXISTS Receipts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Materials_id INTEGER NOT NULL,
  summ REAL NOT NULL,
  date DATE NOT NULL,
  count INTEGER NOT NULL,
  Counterparties_id INTEGER NOT NULL,
  FOREIGN KEY (Materials_id) REFERENCES Materials (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (Counterparties_id) REFERENCES Counterparties (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS Sales;

CREATE TABLE IF NOT EXISTS Sales (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Products_id INTEGER NOT NULL,
  Contracts_id INTEGER NOT NULL,
  summ REAL NOT NULL,
  date DATE NOT NULL,
  FOREIGN KEY (Products_id) REFERENCES Products (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (Contracts_id) REFERENCES Contracts (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);