-- MySQL Script generated by MySQL Workbench
-- Wed Oct 23 11:03:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VacDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `VacDB` ;

-- -----------------------------------------------------
-- Schema VacDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VacDB` DEFAULT CHARACTER SET utf8 ;
USE `VacDB` ;

-- -----------------------------------------------------
-- Table `VacDB`.`Divisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VacDB`.`Divisions` ;

CREATE TABLE IF NOT EXISTS `VacDB`.`Divisions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VacDB`.`Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VacDB`.`Posts` ;

CREATE TABLE IF NOT EXISTS `VacDB`.`Posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VacDB`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VacDB`.`Employees` ;

CREATE TABLE IF NOT EXISTS `VacDB`.`Employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fio` VARCHAR(128) NOT NULL,
  `Divisions_id` INT NOT NULL,
  `Posts_id` INT NOT NULL,
  `dateHire` DATE NOT NULL,
  `dateDismissal` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employees_Divisions_idx` (`Divisions_id` ASC) VISIBLE,
  INDEX `fk_Employees_Posts1_idx` (`Posts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Divisions`
    FOREIGN KEY (`Divisions_id`)
    REFERENCES `VacDB`.`Divisions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_Posts1`
    FOREIGN KEY (`Posts_id`)
    REFERENCES `VacDB`.`Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VacDB`.`Units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VacDB`.`Units` ;

CREATE TABLE IF NOT EXISTS `VacDB`.`Units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VacDB`.`Locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VacDB`.`Locations` ;

CREATE TABLE IF NOT EXISTS `VacDB`.`Locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Employees_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Locations_Employees1_idx` (`Employees_id` ASC) VISIBLE,
  CONSTRAINT `fk_Locations_Employees1`
    FOREIGN KEY (`Employees_id`)
    REFERENCES `VacDB`.`Employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VacDB`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VacDB`.`Products` ;

CREATE TABLE IF NOT EXISTS `VacDB`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `serialNo` VARCHAR(10) NOT NULL,
  `Units_id` INT NOT NULL,
  `Locations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Products_Units1_idx` (`Units_id` ASC) VISIBLE,
  INDEX `fk_Products_Locations1_idx` (`Locations_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Units1`
    FOREIGN KEY (`Units_id`)
    REFERENCES `VacDB`.`Units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Locations1`
    FOREIGN KEY (`Locations_id`)
    REFERENCES `VacDB`.`Locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VacDB`.`Materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VacDB`.`Materials` ;

CREATE TABLE IF NOT EXISTS `VacDB`.`Materials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Units_id` INT NOT NULL,
  `Locations_id` INT NOT NULL,
  `count` INT NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Materials_Units1_idx` (`Units_id` ASC) VISIBLE,
  INDEX `fk_Materials_Locations1_idx` (`Locations_id` ASC) VISIBLE,
  CONSTRAINT `fk_Materials_Units1`
    FOREIGN KEY (`Units_id`)
    REFERENCES `VacDB`.`Units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_Locations1`
    FOREIGN KEY (`Locations_id`)
    REFERENCES `VacDB`.`Locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VacDB`.`Product_Materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VacDB`.`Product_Materials` ;

CREATE TABLE IF NOT EXISTS `VacDB`.`Product_Materials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Products_id` INT NOT NULL,
  `Materials_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_Materials_Products1_idx` (`Products_id` ASC) VISIBLE,
  INDEX `fk_Product_Materials_Materials1_idx` (`Materials_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Materials_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `VacDB`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Materials_Materials1`
    FOREIGN KEY (`Materials_id`)
    REFERENCES `VacDB`.`Materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VacDB`.`Counterparties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VacDB`.`Counterparties` ;

CREATE TABLE IF NOT EXISTS `VacDB`.`Counterparties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `legalAddress` VARCHAR(128) NOT NULL,
  `phoneNomber` VARCHAR(13) NOT NULL,
  `postalAddress` VARCHAR(128) NOT NULL,
  `ynp` VARCHAR(9) NOT NULL,
  `type` ENUM('fiz', 'ur') NOT NULL DEFAULT 'fiz',
  `okulp` VARCHAR(10) NULL,
  `okpo` VARCHAR(10) NULL,
  `oked` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VacDB`.`Contracts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VacDB`.`Contracts` ;

CREATE TABLE IF NOT EXISTS `VacDB`.`Contracts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Counterparties_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `summ` FLOAT NOT NULL,
  `Products_id` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Contracts_Counterparties1_idx` (`Counterparties_id` ASC) VISIBLE,
  INDEX `fk_Contracts_Products1_idx` (`Products_id` ASC) VISIBLE,
  CONSTRAINT `fk_Contracts_Counterparties1`
    FOREIGN KEY (`Counterparties_id`)
    REFERENCES `VacDB`.`Counterparties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contracts_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `VacDB`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VacDB`.`Receipts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VacDB`.`Receipts` ;

CREATE TABLE IF NOT EXISTS `VacDB`.`Receipts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Materials_id` INT NOT NULL,
  `summ` FLOAT NOT NULL,
  `date` DATE NOT NULL,
  `count` INT NOT NULL,
  `Counterparties_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Receipts_Materials1_idx` (`Materials_id` ASC) VISIBLE,
  INDEX `fk_Receipts_Counterparties1_idx` (`Counterparties_id` ASC) VISIBLE,
  CONSTRAINT `fk_Receipts_Materials1`
    FOREIGN KEY (`Materials_id`)
    REFERENCES `VacDB`.`Materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receipts_Counterparties1`
    FOREIGN KEY (`Counterparties_id`)
    REFERENCES `VacDB`.`Counterparties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VacDB`.`Sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VacDB`.`Sales` ;

CREATE TABLE IF NOT EXISTS `VacDB`.`Sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Products_id` INT NOT NULL,
  `Contracts_id` INT NOT NULL,
  `summ` FLOAT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sales_Products1_idx` (`Products_id` ASC) VISIBLE,
  INDEX `fk_Sales_Contracts1_idx` (`Contracts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sales_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `VacDB`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sales_Contracts1`
    FOREIGN KEY (`Contracts_id`)
    REFERENCES `VacDB`.`Contracts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
